
# I2C bus is needed for sensors
i2c:
  id: bus_a
  #scl: D1
  #sda: D2
  #scan: false
  frequency: 50kHz
  #frequency: 400kHz
  
sensor:
  - platform: sht3xd
    temperature:
      name: "Feuchtesensor ${friendly_name}, Temperatur"
      id: sht_temperature
    humidity:
      name: "Feuchtesensor ${friendly_name}, Luftfeuchte"
      id: sht_humidity
    address: 0x45
    update_interval: 60s
    #update_interval: 10s
  - platform: template
    name: "Feuchtesensor ${friendly_name}, Taupunkt"
    lambda: |-
      return (243.5*(log(id(sht_humidity).state/100)+((17.67*id(sht_temperature).state)/
      (243.5+id(sht_temperature).state)))/(17.67-log(id(sht_humidity).state/100)-
      ((17.67*id(sht_temperature).state)/(243.5+id(sht_temperature).state))));
    state_class: measurement
    device_class: temperature
    unit_of_measurement: °C
    icon: 'mdi:thermometer-alert'
