esps_api_pwd:  SOME_API_PASSWORD_OF_YOUR_CHOICE
esps_ota_pwd:  SOME_OTA_PASSWORD_OF_YOUR_CHOICE
esps_fallback_hotspot_pwd: SOME_HOTSPOT_FALLBACK_PASSWORD_OF_YOUR_CHOICE

fritzbox_wlan_sid:  YOUR_WIFI_SID
fritzbox_wlan_pwd:  YOUR_WIFI_PASSWORD
